export const CATEGORY_CREATE = "CREATE/CATEGORY";
export const CATEGORY_UPDATE = "UPDATE/CATEGORY";
export const CATEGORY_DELETE = "DELETE/CATEGORY";
export const CATEGORIES_GET = "GET/CATEGORIES";

export const CATEGORY_CREATE_SUCCESS = "CREATE/CATEGORY_SUCCESS";
export const CATEGORY_UPDATE_SUCCESS = "UPDATE/CATEGORY_SUCCESS";
export const CATEGORY_DELETE_SUCCESS = "DELETE/CATEGORY_SUCCESS";
export const CATEGORIES_GET_SUCCESS = "GET/CATEGORIES_SUCCESS";

export const CATEGORY_CREATE_FAIL = "CREATE/CATEGORY_FAIL";
export const CATEGORY_UPDATE_FAIL = "UPDATE/CATEGORY_FAIL";
export const CATEGORY_DELETE_FAIL = "DELETE/CATEGORY_FAIL";
export const CATEGORIES_GET_FAIL = "GET/CATEGORIES_FAIL";
