export const SECTION_CREATE = "CREATE/SECTION";
export const SECTION_UPDATE = "UPDATE/SECTION";
export const SECTION_DELETE = "DELETE/SECTION";
export const SECTIONS_GET = "GET/SECTIONS";

export const SECTION_CREATE_SUCCESS = "CREATE/SECTION_SUCCESS";
export const SECTION_UPDATE_SUCCESS = "UPDATE/SECTION_SUCCESS";
export const SECTION_DELETE_SUCCESS = "DELETE/SECTION_SUCCESS";
export const SECTIONS_GET_SUCCESS = "GET/SECTIONS_SUCCESS";

export const SECTION_CREATE_FAIL = "CREATE/SECTION_FAIL";
export const SECTION_UPDATE_FAIL = "UPDATE/SECTION_FAIL";
export const SECTION_DELETE_FAIL = "DELETE/SECTION_FAIL";
export const SECTIONS_GET_FAIL = "GET/SECTIONS_FAIL";