export const SECTION_CREATE = "CREATE/SECTION";

export const SECTIONS_GET = "GET/SECTIONS";
export const SECTION_UPDATE = "UPDATE/SECTION";
export const SECTION_DELETE = "DELETE/SECTION";

export const SECTIONS_GET_SUCCESS = "GET/SECTION_SUCCESS";
export const SECTION_CREATE_SUCCESS = "CREATE/SECTION_SUCCESS";
export const SECTION_UPDATE_SUCCESS = "UPDATE/SECTION_SUCCESS";
export const SECTION_DELETE_SUCCESS = "DELETE/SECTION_SUCCESS";

export const SECTIONS_GET_FAIL = "FAIL/SECTION_GET";
export const SECTION_CREATE_FAIL = "FAIL/SECTION_CREATE";
export const SECTION_UPDATE_FAIL = "FAIL/SECTION_UPDATE";
export const SECTION_DELETE_FAIL = "FAIL/SECTION_DELETE";
