export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';

export const NOTE_CREATE = "CREATE/NOTE";
export const NOTE_UPDATE = "UPDATE/NOTE";
export const NOTE_DELETE = "DELETE/NOTE";
export const NOTES_GET = "GET/NOTES";

export const NOTE_CREATE_SUCCESS = "CREATE/NOTE_SUCCESS";
export const NOTE_UPDATE_SUCCESS = "UPDATE/NOTE_SUCCESS";
export const NOTE_DELETE_SUCCESS = "DELETE/NOTE_SUCCESS";
export const NOTES_GET_SUCCESS = "GET/NOTES_SUCCESS";

export const NOTE_CREATE_FAIL = "CREATE/NOTE_FAIL";
export const NOTE_UPDATE_FAIL = "UPDATE/NOTE_FAIL";
export const NOTE_DELETE_FAIL = "DELETE/NOTE_FAIL";
export const NOTES_GET_FAIL = "GET/NOTES_FAIL";
